# Generated by Django 3.0.7 on 2020-07-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('CL', 'Client'), ('PR', 'Practitioner')], max_length=2)),
                ('body', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.Message')),
                ('practitioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='practitioners.Practitioner')),
            ],
        ),
    ]
